// <auto-generated />
using CodeFirts_EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CodeFirts_EF.Migrations
{
    [DbContext(typeof(DbAppContext))]
    [Migration("20240315065421_cascadaGuardado")]
    partial class cascadaGuardado
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("CodeFirts_EF.Models.Genero", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("PeliculaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PeliculaId");

                    b.ToTable("Generos");

                    b.HasData(
                        new
                        {
                            Id = 2,
                            Name = "Terror",
                            PeliculaId = 1
                        },
                        new
                        {
                            Id = 3,
                            Name = "Ciencia-Ficcion",
                            PeliculaId = 1
                        });
                });

            modelBuilder.Entity("CodeFirts_EF.Models.Pelicula", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("peliculas");

                    b.HasData(
                        new
                        {
                            Id = 3,
                            Name = "resident evil"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Amanecer de los muertos"
                        },
                        new
                        {
                            Id = 1,
                            Name = "star wars"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Matrix2"
                        });
                });

            modelBuilder.Entity("CodeFirts_EF.Models.Genero", b =>
                {
                    b.HasOne("CodeFirts_EF.Models.Pelicula", "Pelicula")
                        .WithMany("Generos")
                        .HasForeignKey("PeliculaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pelicula");
                });

            modelBuilder.Entity("CodeFirts_EF.Models.Pelicula", b =>
                {
                    b.Navigation("Generos");
                });
#pragma warning restore 612, 618
        }
    }
}
