// <auto-generated />
using CodeFirts_EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CodeFirts_EF.Migrations
{
    [DbContext(typeof(DbAppContext))]
    [Migration("20240320054814_peliculas50register")]
    partial class peliculas50register
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("CodeFirts_EF.Models.Genero", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("PeliculaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PeliculaId");

                    b.ToTable("Generos");

                    b.HasData(
                        new
                        {
                            Id = 2,
                            Name = "Terror",
                            PeliculaId = 1
                        },
                        new
                        {
                            Id = 3,
                            Name = "Ciencia-Ficcion",
                            PeliculaId = 1
                        });
                });

            modelBuilder.Entity("CodeFirts_EF.Models.Pelicula", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("peliculas");

                    b.HasData(
                        new
                        {
                            Id = 60,
                            Name = "resident evil1"
                        },
                        new
                        {
                            Id = 61,
                            Name = "resident evil2"
                        },
                        new
                        {
                            Id = 62,
                            Name = "resident evil3"
                        },
                        new
                        {
                            Id = 63,
                            Name = "resident evil4"
                        },
                        new
                        {
                            Id = 64,
                            Name = "resident evil5"
                        },
                        new
                        {
                            Id = 65,
                            Name = "resident evil6"
                        },
                        new
                        {
                            Id = 66,
                            Name = "resident evil7"
                        },
                        new
                        {
                            Id = 67,
                            Name = "resident evil8"
                        },
                        new
                        {
                            Id = 68,
                            Name = "resident evil9"
                        },
                        new
                        {
                            Id = 69,
                            Name = "resident evil10"
                        },
                        new
                        {
                            Id = 70,
                            Name = "resident evil11"
                        },
                        new
                        {
                            Id = 71,
                            Name = "resident evil12"
                        },
                        new
                        {
                            Id = 72,
                            Name = "resident evil13"
                        },
                        new
                        {
                            Id = 73,
                            Name = "resident evil14"
                        },
                        new
                        {
                            Id = 74,
                            Name = "resident evil15"
                        },
                        new
                        {
                            Id = 75,
                            Name = "resident evil16"
                        },
                        new
                        {
                            Id = 76,
                            Name = "resident evil17"
                        },
                        new
                        {
                            Id = 77,
                            Name = "resident evil18"
                        },
                        new
                        {
                            Id = 78,
                            Name = "resident evil19"
                        },
                        new
                        {
                            Id = 79,
                            Name = "resident evil20"
                        },
                        new
                        {
                            Id = 80,
                            Name = "resident evil21"
                        },
                        new
                        {
                            Id = 81,
                            Name = "resident evil22"
                        },
                        new
                        {
                            Id = 82,
                            Name = "resident evil23"
                        },
                        new
                        {
                            Id = 83,
                            Name = "resident evil24"
                        },
                        new
                        {
                            Id = 84,
                            Name = "resident evil25"
                        },
                        new
                        {
                            Id = 85,
                            Name = "resident evil26"
                        },
                        new
                        {
                            Id = 86,
                            Name = "resident evil27"
                        },
                        new
                        {
                            Id = 87,
                            Name = "resident evil28"
                        },
                        new
                        {
                            Id = 88,
                            Name = "resident evil29"
                        },
                        new
                        {
                            Id = 89,
                            Name = "resident evil30"
                        },
                        new
                        {
                            Id = 90,
                            Name = "resident evil31"
                        },
                        new
                        {
                            Id = 91,
                            Name = "resident evil32"
                        },
                        new
                        {
                            Id = 92,
                            Name = "resident evil33"
                        },
                        new
                        {
                            Id = 93,
                            Name = "resident evil34"
                        },
                        new
                        {
                            Id = 94,
                            Name = "resident evil35"
                        },
                        new
                        {
                            Id = 95,
                            Name = "resident evil36"
                        },
                        new
                        {
                            Id = 96,
                            Name = "resident evil37"
                        },
                        new
                        {
                            Id = 97,
                            Name = "resident evil38"
                        },
                        new
                        {
                            Id = 98,
                            Name = "resident evil39"
                        },
                        new
                        {
                            Id = 99,
                            Name = "resident evil40"
                        },
                        new
                        {
                            Id = 100,
                            Name = "resident evil41"
                        },
                        new
                        {
                            Id = 101,
                            Name = "resident evil42"
                        },
                        new
                        {
                            Id = 102,
                            Name = "resident evil43"
                        },
                        new
                        {
                            Id = 103,
                            Name = "resident evil44"
                        },
                        new
                        {
                            Id = 104,
                            Name = "resident evil45"
                        },
                        new
                        {
                            Id = 105,
                            Name = "resident evil46"
                        },
                        new
                        {
                            Id = 106,
                            Name = "resident evil47"
                        },
                        new
                        {
                            Id = 107,
                            Name = "resident evil48"
                        },
                        new
                        {
                            Id = 108,
                            Name = "resident evil49"
                        },
                        new
                        {
                            Id = 1,
                            Name = "star wars"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Matrix2"
                        });
                });

            modelBuilder.Entity("CodeFirts_EF.Models.Genero", b =>
                {
                    b.HasOne("CodeFirts_EF.Models.Pelicula", "Pelicula")
                        .WithMany("Generos")
                        .HasForeignKey("PeliculaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pelicula");
                });

            modelBuilder.Entity("CodeFirts_EF.Models.Pelicula", b =>
                {
                    b.Navigation("Generos");
                });
#pragma warning restore 612, 618
        }
    }
}
